apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: LoadBalancer
  selector:
    app: khaddem-backend
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089